"""
Operators used in the Domain Decomposition Method applied to a generic problem 
with rectangular mesh conforming to what is generated by src.common.mesh.mesh()
"""

import numpy as np
from scipy.sparse import csr_matrix
from src.common.helmholtz.system_assembly import mass, stiffness, point_source
from src.seq.operators.s_operator import SFactorization
from src.seq.operators.t_operator import TOperator
from src.seq.operators.b_operator import BOperator
from src.seq.operators.a_operator import AOperator
from src.seq.operators.c_operator import QOperator
from src.seq.operators.pi_operator import PiOperator


# class FullVector(BlockVector):
#     def __init__(self, x: np.ndarray, shapes: list[int]):
#         super(FullVector, self).__init__(x.shape[0])
#         self._x = x
#         self._shapes = shapes

#         # Index at which block j begins
#         # Calculated as a scan sum for all partial sum of shapes
#         self._accShapes = [ shapes[0] if i == 0 
#                            else shapes[i] + self._accShapes[0] 
#                            for i in range(len(shapes))]


#     def getBlock(self, j: int) -> np.ndarray:
#         return self._x[self._accShapes[j]:self._accShapes[j]+self._shapes[j]]
    
#     def getFull(self) -> np.ndarray:
#         return self._x

# class SparseVector(BlockVector):
#     def __init__(self, local_x: np.ndarray, block_idx: int, total_rows: int):
#         super(SparseVector, self).__init__(total_rows)
#         self._block_idx = block_idx
#         self._local_x = local_x

#     def getBlock(self, j: int) -> np.ndarray:
#         if j != self._block_idx:
#             raise ValueError(f"SparseVector.getBlock(): Invalid block_idx j={j}, "
#                              "block_idx is {self._block_idx}")
#         return self._local_x
    
#     def getFull(self) -> np.ndarray:
#         if self._block_idx == 0:
#             # USE MPI4PY HERE TO GATHER X ON 0
#             return self._local_x            

#         return self._local_x

#     def getFullVector(self) -> FullVector:
#         if self._block_idx == 0:
#             # USE MPI4PY HERE TO GATHER X ON 0
#             global_x = np.zeros(0)
#             return FullVector(global_x, shapes=[global_x.shape[0]])

#         return FullVector(self._local_x, shapes=[self._local_x.shape[0]])




