"""
Operators used in the Domain Decomposition Method applied to a generic problem 
with rectangular mesh conforming to what is generated by src.common.mesh.mesh()
"""

import numpy as np
from scipy.sparse import csr_matrix
from src.common.helmholtz.system_assembly import mass, stiffness, point_source
from src.seq.operators.s_operator import SFactorization
from src.seq.operators.t_operator import TOperator
from src.seq.operators.b_operator import BOperator
from src.seq.operators.a_operator import AOperator
from src.seq.operators.c_operator import QOperator
from src.seq.operators.pi_operator import PiOperator


# class FullVector(BlockVector):
#     def __init__(self, x: np.ndarray, shapes: list[int]):
#         super(FullVector, self).__init__(x.shape[0])
#         self._x = x
#         self._shapes = shapes

#         # Index at which block j begins
#         # Calculated as a scan sum for all partial sum of shapes
#         self._accShapes = [ shapes[0] if i == 0 
#                            else shapes[i] + self._accShapes[0] 
#                            for i in range(len(shapes))]


#     def getBlock(self, j: int) -> np.ndarray:
#         return self._x[self._accShapes[j]:self._accShapes[j]+self._shapes[j]]
    
#     def getFull(self) -> np.ndarray:
#         return self._x

# class SparseVector(BlockVector):
#     def __init__(self, local_x: np.ndarray, block_idx: int, total_rows: int):
#         super(SparseVector, self).__init__(total_rows)
#         self._block_idx = block_idx
#         self._local_x = local_x

#     def getBlock(self, j: int) -> np.ndarray:
#         if j != self._block_idx:
#             raise ValueError(f"SparseVector.getBlock(): Invalid block_idx j={j}, "
#                              "block_idx is {self._block_idx}")
#         return self._local_x
    
#     def getFull(self) -> np.ndarray:
#         if self._block_idx == 0:
#             # USE MPI4PY HERE TO GATHER X ON 0
#             return self._local_x            

#         return self._local_x

#     def getFullVector(self) -> FullVector:
#         if self._block_idx == 0:
#             # USE MPI4PY HERE TO GATHER X ON 0
#             global_x = np.zeros(0)
#             return FullVector(global_x, shapes=[global_x.shape[0]])

#         return FullVector(self._local_x, shapes=[self._local_x.shape[0]])

        

def bj_vector(vtxj: np.ndarray, eltj: np.ndarray, 
              sp: list, kappa: float) -> np.ndarray:
    """
    Construct local right-hand side vector bj.
    
    Parameters:
    -----------
    vtxj : ndarray
        Local vertex coordinates
    eltj : ndarray
        Local triangle connectivity
    sp : list
        Point source specifications
    kappa : float
        Wavenumber k
    
    Returns:
    --------
    bj : ndarray
        Local RHS vector
    """
    # Build mass matrix
    M = mass(vtxj, eltj)
    
    # Evaluate point sources at local vertices
    f = point_source(sp, kappa)(vtxj)
    
    # RHS: bj = M @ f
    bj = M @ f
    
    return bj




def g_vector(s_factorization: SFactorization, bj_list: list, B : BOperator, 
             Q: QOperator, nx: int, J: int) -> np.ndarray:
    """
    Construct the global right-hand side vector 'g' for the interface linear system.

    In the DDM formulation, 'g' represents the contribution of the physical 
    volume sources (the RHS of the Helmholtz equation) projected onto the 
    subdomain interfaces.

    Mathematical Definition
    -----------------------
    g = Π ( sum_j C_j^T B_j A_j^{-1} b_j )

    Step-by-step construction:
    1. Solve local problems with zero interface input but full volume source:
       u_j^{local} = (A_{local})^{-1} b_j
    2. Restrict solution to the boundary:
       v_j = B_j u_j^{local}
    3. Assemble into global vector:
       v_{global} = sum (C_j^T v_j)
    4. Apply exchange operator:
       g = Π v_{global}

    Parameters
    ----------
    factorizations : list[scipy.sparse.linalg.SuperLU]
        List of pre-computed LU factorizations for each subdomain operator.
    bj_list : list[np.ndarray]
        List of local volume source vectors (b_j) for each subdomain.
    Bj_list : list[scipy.sparse.csr_matrix]
        List of restriction matrices mapping volume DOFs to boundary DOFs.
    Cj_list : list[scipy.sparse.csr_matrix]
        List of boolean matrices mapping local boundary DOFs to the global 
        interface vector.
    nx : int
        Number of grid points in the x-direction (defines interface size).
    J : int
        Total number of subdomains.

    Returns
    -------
    g : np.ndarray
        The global interface source vector (size: 2 * (J-1) * nx).
    """
    # Determine skeleton size: (J-1) interfaces, 2 sides per interface
    n_skeleton = 2 * (J - 1) * nx
    g_temp = np.zeros(n_skeleton, dtype=complex)
    
    for j in range(J):
        # 1. Solve local problem driven ONLY by volume source bj
        #    (Aj - i B_j^T Tj Bj) uj = bj
        uj = s_factorization.applyLocal(j, bj_list[j])
        
        # 2. Extract trace on the boundary: Bj @ uj
        interface_vals = B.applyLocal(j,uj)
        
        # 3. Map local boundary values to global position
        g_temp += Q.T.applyLocal(j, interface_vals)
    
    # 4. Apply exchange operator to finalize g
    g = PiOperator(J, nx).apply(g_temp)
    
    return g




def uj_solution(xj: np.ndarray, LU_j, Bj: csr_matrix, 
                Tj: csr_matrix, bj: np.ndarray) -> np.ndarray:
    """
    Reconstruct the full local solution u_j using the converged interface data x_j.

    This function acts as the final step of the DDM solver. Once the interface 
    variables x_j (incoming impedance traces) are found, they are used as 
    boundary conditions to solve the local volumetric problem one last time.

    Mathematical Formulation
    ------------------------
    The local system being solved is:
        A_{local} u_j = b_j + B_j^T T_j x_j

    Where:
        u_j = A_{local}^{-1} (b_j + B_j^T T_j x_j)

    Parameters
    ----------
    xj : np.ndarray
        The converged interface data (incoming Robin traces) for this subdomain.
    LU_j : scipy.sparse.linalg.SuperLU
        The pre-computed LU factorization of the local operator 
        (A_j + B_j^T T_j B_j).
    Bj : scipy.sparse.csr_matrix
        The restriction matrix mapping volume DOFs to boundary DOFs.
    Tj : scipy.sparse.csr_matrix
        The transmission (impedance) matrix.
    bj : np.ndarray
        The original local volume source vector (right-hand side).

    Returns
    -------
    np.ndarray
        The fully reconstructed solution vector u_j on the subdomain mesh.
    """
    
    # Map interface data back to volume source terms
    rhs = bj + Bj.T @ (Tj @ xj)
    
    # Solve the local volume problem
    uj = LU_j.solve(rhs)
    
    return uj